import "./global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
      <link rel="shortcut icon" href="/favicon.ico" />
        {children}
      </body>
    </html>
  );
}

